//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saga.Functions
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstantStrings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantStrings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saga.Functions.ConstantStrings", typeof(ConstantStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event with transaction ID = &apos;{0}&apos; created for {1}: ({2} bytes).
        /// </summary>
        internal static string EventCreated
        {
            get
            {
                return ResourceManager.GetString("EventCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity object is null..
        /// </summary>
        internal static string ExceptionMessage
        {
            get
            {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; failed. Message could not be produced: {1}.
        /// </summary>
        internal static string FunctionFailed
        {
            get
            {
                return ResourceManager.GetString("FunctionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error on processing the &apos;{0}&apos; activity, timeout reached..
        /// </summary>
        internal static string TimeoutError
        {
            get
            {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Started orchestration with transaction ID = &apos;{0}&apos;..
        /// </summary>
        internal static string TransactionStarted
        {
            get
            {
                return ResourceManager.GetString("TransactionStarted", resourceCulture);
            }
        }
    }
}
