//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saga.Participants
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstantStrings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantStrings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saga.Participants.ConstantStrings", typeof(ConstantStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account From can not be empty.
        /// </summary>
        internal static string ProcessAccountFromError
        {
            get
            {
                return ResourceManager.GetString("ProcessAccountFromError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error posting event with {0} attempt(s): {1}. Retrying....
        /// </summary>
        internal static string ProcessAccountToError
        {
            get
            {
                return ResourceManager.GetString("ProcessAccountToError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero.
        /// </summary>
        internal static string ProcessAmountError
        {
            get
            {
                return ResourceManager.GetString("ProcessAmountError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transaction can not be empty.
        /// </summary>
        internal static string ProcessTransactionError
        {
            get
            {
                return ResourceManager.GetString("ProcessTransactionError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Receiving from {0}.
        /// </summary>
        internal static string ReceivingMessage
        {
            get
            {
                return ResourceManager.GetString("ReceivingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reverting.
        /// </summary>
        internal static string RevertingMessage
        {
            get
            {
                return ResourceManager.GetString("RevertingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfering to {0}.
        /// </summary>
        internal static string TransferingMessage
        {
            get
            {
                return ResourceManager.GetString("TransferingMessage", resourceCulture);
            }
        }
    }
}
